name: generator
description: Used to generate code automatically
version: 1.0.0

environment:
  sdk: '>=3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  lints: ^2.1.1
  test: ^1.21.0
