name: generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
    sdk: ">=2.19.6 <3.0.0"

dependencies:
    archive:
    dio:
    json_annotation:
    path:

dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
