name: qweather_icons
description: An Icon package for [QWeather](https://github.com/qwd/Icons), which helps you show its icon continently.
version: 0.0.2
homepage: https://github.com/Cierra-Runis/qweather_icons

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: QWeather_Icon
      fonts:
        - asset: assets/fonts/QWeather_Icon.ttf
