name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: flutter pub get

    - name: Build web app
      run: flutter build web --release --web-renderer html --base-href /example/

    - name: Move built files to example directory
      run: mv build/web/* example/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.QWEATHERICONS_TOKEN }}
        publish_dir: ./example/
