name: Build & Deploy qweather_icons

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:

  build-and-deploy:
    name: 'Build & Deploy web app'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Install Flutter and Dart SDK'
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.3.9
          cache: true

      - name: 'Flutter enable Web'
        run: flutter config --enable-web

      - name: 'Get dependencies'
        run: flutter pub get
        working-directory: example/qweather_icons

      - name: 'Build web app'
        run: |
          cd example/qweather_icons
          flutter build web --web-renderer=canvaskit --base-href='/qweather_icons/' --release

      - name: 'Deploy web app'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.QWEATHERICONS_TOKEN }}
          publish_dir: example/qweather_icons/build/web
